name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install

      # Exécuter le build si nécessaire (si tu n'en as pas besoin, tu peux sauter cette étape)
      - name: Build project
        run: npm run build  # Si tu n'as pas de build, cette étape peut être enlevée

      # Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  
          folder: client    
          token: ${{ secrets.GITHUB_TOKEN }} 
          clean: true 
